# Generated by Django 5.1.3 on 2024-11-27 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincourses',
            name='link',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='v1.coursesdetails'),
        ),
    ]
