# Generated by Django 5.1.3 on 2024-12-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_maincourses_experiment_maincourses_features_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maincourses',
            name='period',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_avatar',
            field=models.ImageField(blank=True, db_column='avatar', default='default_avatar.png', upload_to='avatar/'),
        ),
    ]
