# Generated by Django 5.1.3 on 2024-12-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0004_remove_maincourses_period_alter_user_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincourses',
            name='grade',
            field=models.CharField(db_column='grade', max_length=32),
        ),
    ]
