# Generated by Django 5.1.3 on 2024-12-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0007_alter_user_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_avatar',
            field=models.ImageField(blank=True, db_column='avatar', default='default_avatar.png', upload_to=''),
        ),
    ]
