on:
  pull_request:
    branches:
    - dev
jobs:
  deploy:
    name: Deploy to Remote Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ssh deploy
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}
